---

mgmt_node: "node1"
mgmt_disk: sdb
mgmt_mount: "/data/mgmt"

meta_id: 2
meta_disk: sdc
meta_mount: "/data/meta"

storage_id: 3
storage_disk_id: 301
storage_disk: sdb
storage_mount: "/data/d1"

disks:
  mgmt:
    fstype: "ext4"
    mkfs_options: "-F -i 2048 -I 512 -J size=400 -Odir_index,filetype"
    mount_options: "noatime,nodiratime,nobarrier"
  meta:
    fstype: "ext4"
    mkfs_options: "-F -i 2048 -I 512 -J size=400 -Odir_index,filetype"
    mount_options: "noatime,nodiratime,nobarrier"
  storage:
    fstype: "xfs"
    mkfs_options: "-f -d su=128k,sw=8 -l version=2,su=128k -isize=512"
    mount_options: "noatime,nodiratime,logbufs=8,logbsize=256k,largeio,inode64,swalloc,allocsize=131072k,nobarrier"
