---

- name: "[REMOTE] add remote url"
  #command: git remote add origin 'https://{{stash_admin_user}}:{{stash_admin_passwd}}@{{stash_base_url}}/scm/{{git_project_name}}/{{git_repo_name|urlencode()}}.git'
  command: git remote add {{ remote_name }} '{{ remote_url }}'
  args:
    chdir: "{{ git_dest }}"